// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIViIuOYp_m3UUy6I4RSCHfDWdYklRfRw',
    appId: '1:514533526670:web:6b286ec7f40c6f7fbccddf',
    messagingSenderId: '514533526670',
    projectId: 'zoom-clone-a5d73',
    authDomain: 'zoom-clone-a5d73.firebaseapp.com',
    storageBucket: 'zoom-clone-a5d73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfAA5OhmDP2XS1w4vFU4RUjqPatXc1iNI',
    appId: '1:514533526670:android:8da09b71e51bfc71bccddf',
    messagingSenderId: '514533526670',
    projectId: 'zoom-clone-a5d73',
    storageBucket: 'zoom-clone-a5d73.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC6eIZOXtWdvZkRA7hiRU-Ia9g6WLk06E',
    appId: '1:514533526670:ios:6383a9c281ff4b13bccddf',
    messagingSenderId: '514533526670',
    projectId: 'zoom-clone-a5d73',
    storageBucket: 'zoom-clone-a5d73.appspot.com',
    iosClientId:
        '514533526670-3581bcglithpa25mudpf6el1e9vvgvv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIViIuOYp_m3UUy6I4RSCHfDWdYklRfRw',
    appId: '1:514533526670:web:687b16f91b2f48e8bccddf',
    messagingSenderId: '514533526670',
    projectId: 'zoom-clone-a5d73',
    authDomain: 'zoom-clone-a5d73.firebaseapp.com',
    storageBucket: 'zoom-clone-a5d73.appspot.com',
  );
}
